<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-B5L4A4H" failures="1" tests="6" name="testng_Series.testngProg1" time="0.049" errors="0" timestamp="2023-03-02T23:07:18 IST" skipped="2">
  <testcase classname="testng_Series.testngProg1" name="TC3" time="0.018"/>
  <system-out>
    <![CDATA[Execute first Prog of testng TC3]]>
  </system-out>
  <testcase classname="testng_Series.testngProg1" name="Login" time="0.014">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testng_Series.testngProg1.Login(testngProg1.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Login -->
  <system-out/>
  <testcase classname="testng_Series.testngProg1" name="TC1" time="0.009"/>
  <system-out>
    <![CDATA[Execute first Prog of testng TC1]]>
  </system-out>
  <testcase classname="testng_Series.testngProg1" name="TC2" time="0.008"/>
  <system-out>
    <![CDATA[Execute first Prog of testng TC2]]>
  </system-out>
  <testcase classname="testng_Series.testngProg1" name="LogOut" time="0.000">
    <skipped/>
  </testcase> <!-- LogOut -->
  <system-out/>
  <testcase classname="testng_Series.testngProg1" name="TC4">
    <skipped/>
  </testcase> <!-- TC4 -->
  <system-out/>
</testsuite> <!-- testng_Series.testngProg1 -->
